import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import ItemList from "./api/itemlist";
import Register from "@/app/register/page";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className="homePageIntro">
          <h1>Welcome to Game Club!</h1>
          <p>Use the search bar to find the game you are looking for</p>
        </div>
        <div>
          <h1>Items</h1>
          <Register />
          
        </div>
      </main>
    </>
  );
}
